name: Blanc++ Vert

on: [push]

jobs:
  tests:

    # runs-on: ubuntu-latest
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Install Blanc++
        run: sudo add-apt-repository ppa:conr2d/blanc -y && sudo apt install blanc clang-12 lld-12 binaryen -y

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
          # node-version: '19.x'
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn test